FROM postgres:latest


RUN apt-get update && apt-get install -y wget git \
    && wget https://golang.org/dl/go1.21.0.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz \
    && rm go1.21.0.linux-amd64.tar.gz


ENV PATH=$PATH:/usr/local/go/bin


WORKDIR /app


COPY . .

RUN go mod tidy

COPY init.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/init.sh