version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MIGRATIONS_COMMAND=go run db_migrator/main.go db_migrator/migrations.go
      - PORT=3003
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_NAME=hoteldb
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=info.mailavail@gmail.com
      - MAIL_PASSWORD=kyuqssyrhjquhvef
    depends_on:
      - postgres
    command: sh -c "${MIGRATIONS_COMMAND} && ./main"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: